### ISSUE TITLE
Why have you removed the changelog?

### ISSUE THREAD

**Issue by galapogos01** [AddressFinder/addressfinder-woocommerce#55]
Why have you removed the changelog from both here & the official plugin repo?

Site operators need to know what's changed with each version.

**Comment by vprigent** [comment]
Hi Jason,

The changelog was removed from the readme.txt file as it exists as a standalone file [here](https://github.com/AddressFinder/addressfinder-woocommerce/blob/master/changelog.txt)

**Comment by galapogos01** [comment]
Thanks - would be appreciated if you could add it back to the official WP plugin repo.

**Comment by vprigent** [comment]
Hi Jason,

We've made adjustments to the changelog, it should be back on the WP plugin repo too.

Thanks for reporting the issue!
